name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          cd client && npm install
          cd ../server && npm install

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Deploy to Railway
        uses: railwayapp/action@v1
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          project-id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment: production
          service-name: "mern-exercise-tracker" # Changed to match your Railway service name
          variables: |
            ATLAS_URI=${{ secrets.ATLAS_URI }}
            PORT=5000
            NODE_ENV=production
            VITE_API_URL=https://mern-exercise-tracker-production-cdae.up.railway.app
